services:
  backend:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/backend
      - ~/.aws/:/root/.aws:ro
    ports:
      - 5000:5000
    environment:
      - TODO_LIST_TABLE=TodoListTableV2
  frontend:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/frontend
    ports:
      - 5001:5001
